import Footer from '../components/Footer';
import Header from '../components/Header';
import './globals.css';
import { Jost, Manrope } from 'next/font/google';

const jost = Jost({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-jost',
});
const manrope = Manrope({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-manrope',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${jost.variable} ${manrope.variable} antialiased font-manrope bg-light text-darkOffset dark:bg-dark dark:text-lightOffset`}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
